version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: vishwakarma_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vishwakarma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: vishwakarma_redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    container_name: vishwakarma_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
